config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  get "chats/:id" => "chats#show", as: "chat"
  get "cate_search" => "homes#cate_search"

  resources :users do
    resource :relationships, only: [:create, :destroy]
     get :follows, on: :member
     get :followers, on: :member
     get :count_search, on: :member
  end

  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :chats, only: [:create]
  resources :groups do
    get :join, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  is_impressionable

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  validates :rate, presence: true, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }

  belongs_to :user
  has_many :favorites
  has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 13.day.ago.beginning_of_day..1.week.ago.end_of_day) }


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(word, search)
    if search == "perfect_match"
      Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      Book.where("title LIKE?", "#{word}%")
    elsif search == "backword_match"
      Book.where("title LIKE?", "%#{word}")
    elsif search == "backword_match"
      Book.where("title LIKE?", "%#{word}%")
    else
      Book.all
    end
  end

  def self.cate_search(search)
    Book.where("category LIKE?", "#{search}")
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  validates :comment, presence: true

  belongs_to :user
  belongs_to :book
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, length: {maximum: 140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  attachment :image

  has_many :group_users
  has_many :users, through: :group_users
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id, dependent: :destroy
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :following

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, dependent: :destroy

  def followed_by?(user)
    passive_relationships.where(following_id: user.id).exists?
  end

  def self.looks(word, search)
    if search == "perfect_match"
      User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      User.where("name LIKE?", "#{word}%")
    elsif search == "backword_match"
      User.where("name LIKE?", "%#{word}")
    elsif search == "backword_match"
      User.where("name LIKE?", "%#{word}%")
    else
      User.all
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   impressionist :actions=> [:show], unique: [:ip_address]

  def index
    @book = Book.new
    @user = current_user
    #to = Time.zone.now.end_of_day
    #from = 6.day.ago.beginning_of_day
    #@books = Book.includes(:favorited_users).sort{|a,b|
      #b.favorited_users.includes(:favorites).where(created_at: from..to).size <=>
      #a.favorited_users.includes(:favorites).where(created_at: from..to).size
    #}
    @books = Book.all.order(params[:sort])
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @comment = BookComment.new
    impressionist(@book, nil, unique: [:ip_address])
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :body, :rate, :category)
    end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_room = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    if user_room.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    else
      @room = user_room.room
    end

    @chat = Chat.new(room_id: @room.id)
    @chats = @room.chats
  end

  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
  end

  private
    def chat_params
      params.require(:chat).permit(:message, :room_id)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def cate_search
    @book = Book.new
    @books = Book.cate_search(params[:keyword])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    @the_day_before = @today_book.count / @yesterday_book.count.to_f
    @the_week_before = @this_week_book.count / @last_week_book.count.to_f
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  def count_search
    @user = User.find(params[:id])
    @books = @user.books
    create_at = params[:created_at]
    @count_search = @books.where("created_at LIKE?", "#{create_at}%").count
  end

  private
    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error.html.erb
<div class="error">
    <% if model.errors.any? %>
      <% if model.errors.count == 1 %>
        <h3><%= model.errors.count  %> error prohibited this obj from being saved:</h3>
      <% else %>
        <h3><%= model.errors.count  %> errors prohibited this obj from being saved:</h3>
      <% end %>
      <% model.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    <% end %>
</div>

app/views/books/_form.html.erb
  <h2 class="mt-3">New book</h2>
  <%= form_with model: book, local: true do |f| %>
    <div class="form-group">
      <%= f.label :Title %>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :Opinion %>
      <%= f.text_area :body, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :Category %>
      <%= f.text_field :category, class:"form-control" %>
    </div>
    <div id="star" class="form-group">
      <%= f.label :Rate %>
      <%= f.hidden_field :rate, class:"form-control" %>
    </div>
    <script>
      $('#star').raty({
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        scoreName: 'book[rate]',
        half: true
      });
    </script>
    <%= f.submit "Create Book", class:"btn btn-success" %>
  <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mt-3 mx-auto">
      <h1>Editing Book</h1>
      <%= render "books/error", model: @book %>
      <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <%= f.label :Title %>
          <%= f.text_field :title, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :Opinion %>
          <%= f.text_area :body, class:"form-control" %>
        </div>
        <%= f.submit "Update Book", class:"btn btn-success" %>
      <% end %>
      <div class="mt-3">
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container mt-3">
  <%= render "books/error", model: @book %>
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= link_to "新着順", books_path(sort: "created_at DESC") %> |
      <%= link_to "評価の高い順", books_path(sort: "rate DESC") %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40"  %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td><%= book.body %></td>
              <td id="favorite_btn_<%= book.id %>">
                <%= render "favorites/favorite", book: book %>
              </td>
              <td>コメント数：<%= book.book_comments.count %></td>
              <td>
                <div id="rate_<%= book.id %>"></div>
                <script>
                $('#rate_<%= book.id %>').raty({
                  size: 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= book.rate %>
                });
              </script>
              </td>
              <td>閲覧数：<%= book.impressionist_count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/form", book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %><br>
                <%= @user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book) %>
            </td>
            <td><%= @book.body %></td>
            <td><%= @book.category %></td>
            <td id="favorite_btn_<%= @book.id %>">
              <%= render "favorites/favorite", book: @book %>
            </td>
            <td id="comment_count">コメント数：<%= @book.book_comments.count %></td>
            <td>
              <div id="rate_<%= @book.id %>"></div>
              <script>
                $('#rate_<%= @book.id %>').raty({
                  size: 36,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= @book.rate %>
                });
              </script>
            </td>
            <td>閲覧数：<%= @book.impressionist_count %></td>
            <% if @user == current_user %>
              <td>
                <%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book), method: :delete, data:{confirm: "本当に消しますか？"}, class:"btn btn-sm btn-danger" %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <table>
        <tbody id="comment_area">
          <%= render "book_comments/comment", book: @book %>
        </tbody>
      </table>
      <%= form_with model: [@book, @comment] do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, rows:"5", class:"form-control" %>
        </div>
        <%= f.submit "送信" %>
      <% end %>
    </div>
  </div>
</div>

app/views/chats/create.js.erb
$('.message').append("<p style='text-align: left;'><%= @chat.message %></p>")
$('input[type=text]').val('')

app/views/chats/show.html.erb
<h2><%= @user.name %>さんとのチャット</h2>
<div class="col-md-10">
  <table class="message table table-borderless">
    <% @chats.each do |chat| %>
      <% if chat.user == current_user %>
        <tbody>
          <tr>
            <td>
              <p style="text-align: left;"><%= chat.message %></p>
            </td>
          </tr>
        </tbody>
      <% else %>
        <tbody>
          <tr>
            <td>
              <p style="text-align: right;"><%= chat.message %></p>
            </td>
          </tr>
        </tbody>
      <% end %>
    <% end %>
  </table>
  <%= form_with model: @chat do |f| %>
    <%= f.text_field :message %>
    <%= f.hidden_field :room_id %>
  <% end %>
</div>

app/views/users/_count.html.erb
<h2>検索結果</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= count_search %></td>
    </tr>
  </tbody>
</table>

app/views/users/_follow.html.erb
<% if users.present? %>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %></td>
          <td><%= user.name %></td>
          <td>フォロー数<%= user.active_relationships.count %></td>
          <td>フォロワー数<%= user.passive_relationships.count %></td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  ユーザーはいません
<% end %>

app/views/users/_info.html.erb
<h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "100x100" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th><%= link_to user.active_relationships.count, follows_user_path(user) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to user.passive_relationships.count, followers_user_path(user) %></th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <% if user == current_user  %>
      <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% elsif user.followed_by?(current_user) %>
      <%= link_to "フォロー外す",  user_relationships_path(user), method: :delete, class: "btn btn-info btn-sm" %>
    <% else %>
      <%= link_to "フォローする",  user_relationships_path(user), method: :post, class: "btn btn-success btn-sm" %>
    <% end %>

    <% if user.followed_by?(current_user) && current_user.followed_by?(user) %>
      <%= link_to "chatを始める", chat_path(user) %>
    <% end %>
  </div>

app/views/users/count_search.js.erb
$('#search_result').html("<%= j(render "users/count", count_search: @count_search) %>")

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mt-3 mx-auto">
      <h2>User info</h2>
      <%= render "books/error", model: @user %>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :Name %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :Image %>
          <%= f.attachment_field :profile_image, class:"form-control-file" %>
        </div>
        <div class="form-group">
          <%= f.label :Introduction %>
          <%= f.text_area :introduction, class:"form-control" %>
        </div>
        <%= f.submit "Update User", class:"btn btn-secondary" %>
      <% end %>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<%= render "users/follow", users: @users %>

app/views/users/follows.html.erb
<h2>Follow Users</h2>
<%= render "users/follow", users: @users %>

app/views/users/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> |
      <%= link_to "グループ一覧", groups_path %>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %></td>
              <td><%= user.name %></td>
              <td>フォロー数：<%= user.active_relationships.count %></td>
              <td>フォロワー数：<%= user.passive_relationships.count %></td>
              <td>
                <% if user != current_user %>
                  <% if user.followed_by?(current_user) %>
                    <%= link_to "フォロー外す",  user_relationships_path(user), method: :delete %>
                  <% else %>
                    <%= link_to "フォローする",  user_relationships_path(user), method: :post %>
                  <% end %>
                <% end %>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-3">
  <%= render "books/error", model: @user %>
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                  <%= attachment_image_tag @user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book) %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <h2>投稿数の前日比・前週比</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @today_book.count %></td>
            <td><%= @yesterday_book.count %></td>
            <td>
              <% if @yesterday_book.count == 0 %>
                前日の投稿数が0のため計算できませんでした
              <% else %>
                <%= (@the_day_before * 100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @this_week_book.count %></td>
            <td><%= @last_week_book.count %></td>
            <td>
              <% if @last_week_book.count == 0 %>
                前週の投稿数が0のため計算できませんでした
              <% else %>
                <%= (@the_week_before * 100).round %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <%= form_with url: count_search_user_path(@user), method: :get do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit "検索", class: "btn btn-primary" %>
      <% end %>
      <div id="search_result">
        <% if @count_search.present? %>
          <%= render "users/count", count_search: @count_search %>
        <% end %>
      </div>
    </div>

  </div>
</div>